# Generated by Django 2.2 on 2019-09-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя автора')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('text', models.TextField(max_length=2000, verbose_name='текст записи')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('edit', models.DateTimeField(auto_now=True, verbose_name='время редактирования')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
